name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.14.0
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image for Profile Website
        uses: docker/build-push-action@v2
        with:
          context: profile_website
          file: ./Dockerfile
          push: true
          tags: kjaehyeok21/profile_website_web:latest
      - name: Trigger jenkins job
        uses: joshlk/jenkins-githubaction@master
        with:
          url: https://kjaehyeok21.dev:8081
          job_name: profile_website
          username: ${{ secrets.JENKINS_USER }}
          api_token: ${{ secrets.JENKINS_TOKEN }}
          timeout: "1000"
      
